# Generated by Django 3.2 on 2021-04-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='passengerinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='passengerinfo',
            name='otch',
        ),
    ]
