# Generated by Django 3.2 on 2021-04-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20210425_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassengerInfo',
            new_name='AquariumInfo',
        ),
    ]
