# Generated by Django 3.2 on 2021-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_passengerinfo_aquariuminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquariuminfo',
            name='city',
            field=models.CharField(default='migrations', max_length=40),
        ),
        migrations.AddField(
            model_name='aquariuminfo',
            name='email',
            field=models.CharField(default='aaa', max_length=40),
        ),
        migrations.AddField(
            model_name='aquariuminfo',
            name='fam_name',
            field=models.CharField(default='hello', max_length=40),
        ),
        migrations.AddField(
            model_name='aquariuminfo',
            name='fat_name',
            field=models.CharField(default='do', max_length=40),
        ),
        migrations.AddField(
            model_name='aquariuminfo',
            name='fir_name',
            field=models.CharField(default='pls', max_length=40),
        ),
        migrations.AddField(
            model_name='aquariuminfo',
            name='sign',
            field=models.TextField(default='signing'),
        ),
        migrations.AddField(
            model_name='aquariuminfo',
            name='tank_amount',
            field=models.IntegerField(default=0),
        ),
    ]
